CREATE TABLE TIPO_PAGAMENTO
(
    ID          NUMBER       NOT NULL,
    DESCRICAO   VARCHAR2(20) NOT NULL,
    DATA_INSERT TIMESTAMP    NOT NULL,
    DATA_UPDATE TIMESTAMP    NOT NULL,
    PRIMARY KEY (ID)
);