CREATE TABLE PLANO_CONTA
(
    ID          NUMBER        NOT NULL,
    DESCRICAO   VARCHAR2(100) NOT NULL,
    DATA_INSERT TIMESTAMP     NOT NULL,
    DATA_UPDATE TIMESTAMP     NOT NULL,
    PRIMARY KEY (ID)
);