CREATE TABLE CLIENTE
(
    ID                 NUMBER        NOT NULL,
    NOME               VARCHAR2(100) NOT NULL,
    CPF                VARCHAR2(11)  NOT NULL,
    RG                 VARCHAR2(15)  NOT NULL,
    RG_ORGAO_EXPEDITOR VARCHAR2(10)  NOT NULL,
    DATA_NASCIMENTO    DATE          NOT NULL,
    PROFISSAO          VARCHAR2(100),
    EMPRESA            VARCHAR2(100),
    RENDA              DECIMAL(5, 2),
    REFERENCIA         VARCHAR2(50),
    OBSERVACAO         VARCHAR2(500),
    DATA_INSERT        TIMESTAMP     NOT NULL,
    DATA_UPDATE        TIMESTAMP     NOT NULL,
    PRIMARY KEY (ID)
);