CREATE TABLE CLIENTE_ENDERECO
(
    ID          NUMBER       NOT NULL,
    CLIENTE_ID  NUMBER       NOT NULL,
    RUA         VARCHAR(50)  NOT NULL,
    NUMERO      VARCHAR(10)  NOT NULL,
    COMPLEMENTO VARCHAR(50),
    CEP         VARCHAR(8)   NOT NULL,
    BAIRRO      VARCHAR(50)  NOT NULL,
    CIDADE      VARCHAR(100) NOT NULL,
    UD          CHAR(2)      NOT NULL,
    DATA_INSERT TIMESTAMP    NOT NULL,
    DATA_UPDATE TIMESTAMP    NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
);