CREATE TABLE CLIENTE_ENDERECO
(
    ID          NUMBER        NOT NULL,
    CLIENTE_ID  NUMBER        NOT NULL,
    RUA         VARCHAR2(50)  NOT NULL,
    NUMERO      VARCHAR2(10)  NOT NULL,
    COMPLEMENTO VARCHAR2(50),
    CEP         VARCHAR2(8)   NOT NULL,
    BAIRRO      VARCHAR2(50)  NOT NULL,
    CIDADE      VARCHAR2(100) NOT NULL,
    UD          CHAR(2)       NOT NULL,
    DATA_INSERT TIMESTAMP     NOT NULL,
    DATA_UPDATE TIMESTAMP     NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
);