CREATE TABLE CLIENTE_CONTATO
(
    ID          NUMBER    NOT NULL,
    CLIENTE_ID  NUMBER    NOT NULL,
    TIPO        VARCHAR2(10),
    EMAIL       VARCHAR2(50),
    TELEFONE    VARCHAR2(15),
    OBSERVACAO  VARCHAR2(500),
    DATA_INSERT TIMESTAMP NOT NULL,
    DATA_UPDATE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
);