CREATE TABLE BANCO
(
    ID          NUMBER       NOT NULL,
    NOME        VARCHAR2(20) NOT NULL,
    AGENCIA     VARCHAR2(10) NOT NULL,
    CONTA       VARCHAR2(10) NOT NULL,
    GERENTE     VARCHAR2(20),
    OBSERVACAO  VARCHAR2(500),
    DATA_INSERT TIMESTAMP    NOT NULL,
    DATA_UPDATE TIMESTAMP    NOT NULL,
    PRIMARY KEY (ID)
);