CREATE TABLE DEPARTAMENTO
(
    ID          NUMBER       NOT NULL,
    NOME        VARCHAR2(20) NOT NULL,
    DATA_INSERT TIMESTAMP    NOT NULL,
    DATA_UPDATE TIMESTAMP    NOT NULL,
    PRIMARY KEY (ID)
);