CREATE SEQUENCE SEQUENCE_TIPO_PAGAMENTO START WITH 1 INCREMENT BY 1;

CREATE TABLE TIPO_PAGAMENTO
(
    ID          NUMBER       NOT NULL,
    DESCRICAO   VARCHAR2(20) NOT NULL,
    DATA_INSERT TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);