CREATE SEQUENCE SEQUENCE_PLANO_CONTA START WITH 1 INCREMENT BY 1;

CREATE TABLE PLANO_CONTA
(
    ID          NUMBER        NOT NULL,
    DESCRICAO   VARCHAR2(100) NOT NULL,
    DATA_INSERT TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);