CREATE SEQUENCE SEQUENCE_VENDA_DETALHE START WITH 1 INCREMENT BY 1;

CREATE TABLE VENDA_DETALHE
(
    QUANTIDADE         NUMBER         NOT NULL,
    VALOR_UNITARIO     DECIMAL(10, 2) NOT NULL,
    VALOR_TOTAL        DECIMAL(10, 2) NOT NULL,
    DATA_INSERT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VENDA_CABECALHO_ID NUMBER         NOT NULL,
    PRODUTO_ID         NUMBER         NOT NULL,
    PRIMARY KEY (VENDA_CABECALHO_ID, PRODUTO_ID),
    FOREIGN KEY (VENDA_CABECALHO_ID) REFERENCES VENDA_CABECALHO (ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (ID)
);