CREATE SEQUENCE SEQUENCE_NOTA_FISCAL_CABECALHO START WITH 1 INCREMENT BY 1;

CREATE TABLE NOTA_FISCAL_CABECALHO
(
    ID            NUMBER         NOT NULL,
    NUMERO        VARCHAR2(10)   NOT NULL,
    VALOR_TOTAL   DECIMAL(10, 2) NOT NULL,
    DATA_EMISSAO  DATE           NOT NULL,
    DATA_ENTRADA  DATE           NOT NULL,
    DATA_INSERT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FORNECEDOR_ID NUMBER         NOT NULL,
    CFOP_ID       NUMBER         NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR (ID),
    FOREIGN KEY (CFOP_ID) REFERENCES CFOP (ID)
);