CREATE SEQUENCE SEQUENCE_NOTA_FISCAL_DETALHE START WITH 1 INCREMENT BY 1;

-- TODO: ADICIONAR DEMAIS CAMPOS
CREATE TABLE NOTA_FISCAL_DETALHE
(
    ID                       NUMBER         NOT NULL,
    QUANTIDADE               NUMBER         NOT NULL,
    VALOR_UNITARIO           DECIMAL(10, 2) NOT NULL,
    DATA_INSERT              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NOTA_FISCAL_CABECALHO_ID NUMBER         NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (NOTA_FISCAL_CABECALHO_ID) REFERENCES NOTA_FISCAL_CABECALHO (ID)
);