-- TODO: FAZER RELACIONAMENTO COM TABELA DE USUÁRIO
CREATE TABLE REQUISICAO_CABECALHO
(
    ID              NUMBER    NOT NULL,
    DATA_REQUISICAO DATE      NOT NULL,
    DATA_INSERT     TIMESTAMP NOT NULL,
    DATA_UPDATE     TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);