CREATE SEQUENCE SEQUENCE_COTACAO START WITH 1 INCREMENT BY 1;

CREATE TABLE COTACAO
(
    ID           NUMBER NOT NULL,
    DATA_COTACAO DATE   NOT NULL,
    DATA_INSERT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);