CREATE TABLE COTACAO_FORNECEDOR_CABECALHO
(
    ID            NUMBER         NOT NULL,
    CONDICOES     VARCHAR2(30)   NOT NULL,
    DESCONTO      DECIMAL(10, 2) NOT NULL,
    ENTREGA       VARCHAR2(30)   NOT NULL,
    TOTAL         DECIMAL(10, 2) NOT NULL,
    DATA_INSERT   TIMESTAMP      NOT NULL,
    DATA_UPDATE   TIMESTAMP      NOT NULL,
    COTACAO_ID    NUMBER         NOT NULL,
    FORNECEDOR_ID NUMBER         NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (COTACAO_ID) REFERENCES COTACAO (ID),
    FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR (ID)
);