CREATE SEQUENCE SEQUENCE_PEDIDO_CABECALHO START WITH 1 INCREMENT BY 1;

CREATE TABLE PEDIDO_CABECALHO
(
    ID            NUMBER         NOT NULL,
    DATA_PEDIDO   DATE           NOT NULL,
    VALOR         DECIMAL(10, 2) NOT NULL,
    DESCONTO      DECIMAL(10, 2) NOT NULL,
    TOTAL         DECIMAL(10, 2) NOT NULL,
    DATA_INSERT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COTACAO_ID    NUMBER         NOT NULL,
    FORNECEDOR_ID NUMBER         NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (COTACAO_ID) REFERENCES COTACAO (ID),
    FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR (ID)
);