CREATE TABLE PEDIDO_DETALHE
(
    QUANTIDADE            NUMBER         NOT NULL,
    VALOR_UNITARIO        DECIMAL(10, 2) NOT NULL,
    VALOR_TOTAL           DECIMAL(10, 2) NOT NULL,
    DATA_INSERT           TIMESTAMP      NOT NULL,
    DATA_UPDATE           TIMESTAMP      NOT NULL,
    PEDIDO_CABECALHO_ID   NUMBER         NOT NULL,
    COTACAO_DETALHE_ID    NUMBER         NOT NULL,
    REQUISICAO_DETALHE_ID NUMBER         NOT NULL,
    PRODUTO_ID            NUMBER         NOT NULL,
    PRIMARY KEY (PEDIDO_CABECALHO_ID, COTACAO_DETALHE_ID, REQUISICAO_DETALHE_ID, PRODUTO_ID),
    FOREIGN KEY (PEDIDO_CABECALHO_ID) REFERENCES PEDIDO_CABECALHO (ID),
    FOREIGN KEY (COTACAO_DETALHE_ID) REFERENCES COTACAO_DETALHE (ID),
    FOREIGN KEY (REQUISICAO_DETALHE_ID) REFERENCES REQUISICAO_DETALHE (ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (ID)
);