CREATE TABLE PEDIDO_CABECALHO_ENDERECO
(
    PEDIDO_CABECALHO_ID  NUMBER NOT NULL,
    ENDERECO_ENTREGA_ID  NUMBER NOT NULL,
    ENDERECO_COBRANCA_ID NUMBER NOT NULL,
    PRIMARY KEY (PEDIDO_CABECALHO_ID, ENDERECO_ENTREGA_ID, ENDERECO_COBRANCA_ID),
    FOREIGN KEY (PEDIDO_CABECALHO_ID) REFERENCES PEDIDO_CABECALHO (ID),
    FOREIGN KEY (ENDERECO_ENTREGA_ID) REFERENCES ENDERECO (ID),
    FOREIGN KEY (ENDERECO_COBRANCA_ID) REFERENCES ENDERECO (ID)
);