CREATE TABLE MOVIMENTO
(
    ID               NUMBER         NOT NULL,
    MES              CHAR(2)        NOT NULL,
    ANO              CHAR(4)        NOT NULL,
    NUMERO_DOCUMENTO VARCHAR2(20)   NOT NULL,
    DATA_LANCAMENTO  DATE           NOT NULL,
    HISTORICO        VARCHAR2(50)   NOT NULL,
    VALOR_DOCUMENTO  DECIMAL(10, 2) NOT NULL,
    DATA_INSERT      TIMESTAMP      NOT NULL,
    DATA_UPDATE      TIMESTAMP      NOT NULL,
    PLANO_CONTA_ID   NUMBER         NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PLANO_CONTA_ID) REFERENCES PLANO_CONTA (ID)
);