CREATE SEQUENCE SEQUENCE_ORCAMENTO_CABECALHO START WITH 1 INCREMENT BY 1;

CREATE TABLE ORCAMENTO_CABECALHO
(
    ID             NUMBER         NOT NULL,
    DATA_ORCAMENTO DATE           NOT NULL,
    VALOR          DECIMAL(10, 2) NOT NULL,
    DATA_INSERT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CLIENTE_ID     NUMBER         NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
);