CREATE SEQUENCE SEQUENCE_CONTATO START WITH 1 INCREMENT BY 1;

CREATE TABLE CONTATO
(
    ID          NUMBER    NOT NULL,
    NOME        VARCHAR2(100),
    EMAIL       VARCHAR2(50),
    TELEFONE    VARCHAR2(15),
    OBSERVACAO  VARCHAR2(500),
    DATA_INSERT TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);