CREATE SEQUENCE SEQUENCE_CLIENTE START WITH 1 INCREMENT BY 1;

CREATE TABLE CLIENTE
(
    ID                 NUMBER        NOT NULL,
    NOME               VARCHAR2(100) NOT NULL,
    CPF                VARCHAR2(11)  NOT NULL,
    RG                 VARCHAR2(15)  NOT NULL,
    RG_ORGAO_EXPEDITOR VARCHAR2(10)  NOT NULL,
    DATA_NASCIMENTO    DATE          NOT NULL,
    PROFISSAO          VARCHAR2(100),
    EMPRESA            VARCHAR2(100),
    RENDA              DECIMAL(5, 2),
    OBSERVACAO         VARCHAR2(500),
    DATA_INSERT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ENDERECO_ID        NUMBER        NOT NULL,
    CONTATO_ID         NUMBER        NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ID),
    FOREIGN KEY (CONTATO_ID) REFERENCES CONTATO (ID)
);