CREATE SEQUENCE SEQUENCE_FORNECEDOR START WITH 1 INCREMENT BY 1;

CREATE TABLE FORNECEDOR
(
    ID          NUMBER        NOT NULL,
    NOME        VARCHAR2(100) NOT NULL,
    CNPJ        VARCHAR2(14)  NOT NULL,
    OBSERVACAO  VARCHAR2(500),
    DATA_INSERT TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    ENDERECO_ID NUMBER        NOT NULL,
    CONTATO_ID  NUMBER        NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ID),
    FOREIGN KEY (CONTATO_ID) REFERENCES CONTATO (ID)
);