CREATE SEQUENCE SEQUENCE_BANCO START WITH 1 INCREMENT BY 1;

CREATE TABLE BANCO
(
    ID          NUMBER       NOT NULL,
    NOME        VARCHAR2(20) NOT NULL,
    AGENCIA     VARCHAR2(10) NOT NULL,
    CONTA       VARCHAR2(10) NOT NULL,
    GERENTE     VARCHAR2(20),
    OBSERVACAO  VARCHAR2(500),
    DATA_INSERT TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);