CREATE SEQUENCE SEQUENCE_UNIDADE START WITH 1 INCREMENT BY 1;

CREATE TABLE UNIDADE
(
    ID          NUMBER     NOT NULL,
    DESCRICAO   VARCHAR(5) NOT NULL,
    DATA_INSERT TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);