CREATE SEQUENCE SEQUENCE_DEPARTAMENTO START WITH 1 INCREMENT BY 1;

CREATE TABLE DEPARTAMENTO
(
    ID          NUMBER       NOT NULL,
    NOME        VARCHAR2(20) NOT NULL,
    DATA_INSERT TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);