CREATE SEQUENCE SEQUENCE_CFOP START WITH 1 INCREMENT BY 1;

CREATE TABLE CFOP
(
    ID          NUMBER         NOT NULL,
    CODIGO      VARCHAR2(5)    NOT NULL,
    DESCRICAO   VARCHAR2(1024) NOT NULL,
    APLICACAO   VARCHAR2(2024) NOT NULL,
    DATA_INSERT TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DATA_UPDATE TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);