CREATE TABLE CFOP
(
    ID          NUMBER         NOT NULL,
    CODIGO      VARCHAR2(5)    NOT NULL,
    DESCRICAO   VARCHAR2(1024) NOT NULL,
    APLICACAO   VARCHAR2(2024) NOT NULL,
    DATA_INSERT TIMESTAMP      NOT NULL,
    DATA_UPDATE TIMESTAMP      NOT NULL,
    PRIMARY KEY (ID)
);