version: "3"

services:

  oracle:
    container_name: oracle-database
    image: gvenzl/oracle-free
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_DATABASE: "OKKSISCOMDB"
      ORACLE_RANDOM_PASSWORD: "true"
      APP_USER: "okksiscomdbuser"
      APP_USER_PASSWORD: "okksiscomdbpassword"
    deploy:
      resources:
        limits:
          memory: 4GB
        reservations:
          memory: 4GB
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
    driver: local